# nix/default.nix — Package derivation for rofi-suite
#
# Builds the rofi-suite by running build-theme.sh and packaging
# the result along with scripts and config.
#
# The optional colorSchemeFile parameter allows injecting a custom
# color scheme (e.g., stylix.rasi generated by the HM module).
#
# Usage (from flake):
#   nix build .#default
#   nix build .#default --override-input colorScheme ./path/to/custom.rasi

{ lib
, stdenv
, bash
, jq
, src ? ./..
, colorSchemeName ? null
, colorSchemeFile ? null
}:

stdenv.mkDerivation {
  pname = "rofi-suite";
  version = "unstable";

  inherit src;

  nativeBuildInputs = [ bash jq ];

  postPatch = ''
    chmod +x build-theme.sh 2>/dev/null || true
    chmod +x bin/* 2>/dev/null || true
  '';

  dontConfigure = true;

  buildPhase = ''
    runHook preBuild

    # If a custom color scheme file was provided, inject it into templates
    ${lib.optionalString (colorSchemeFile != null && colorSchemeName != null) ''
      if [ -f "${colorSchemeFile}" ]; then
        mkdir -p "templates/colors"
        cp "${colorSchemeFile}" "templates/colors/${colorSchemeName}.rasi"
        echo "→ Injected custom color scheme: ${colorSchemeName}"
      fi
    ''}

    # Determine which color scheme to build with
    COLOR_FLAG=""
    ${if colorSchemeName != null then ''
      COLOR_FLAG="--color ${colorSchemeName}"
    '' else ''# Use whatever is in the config''}

    bash ./build-theme.sh --output "$out/share/rofi-suite" $COLOR_FLAG

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p "$out/share/rofi-suite/bin"

    # Install scripts
    if [ -d bin ]; then
      cp -r bin/* "$out/share/rofi-suite/bin/"
      chmod +x "$out/share/rofi-suite/bin/"*
    fi

    # Install config files
    cp defaults.json "$out/share/rofi-suite/" 2>/dev/null || true

    runHook postInstall
  '';

  meta = with lib; {
    description = "Modular rofi theme suite — DRY, config-driven, NixOS-friendly";
    license = licenses.mit;
    platforms = platforms.unix;
  };
}
