# nix/stylix.nix — Home Manager module for rofi-suite with Stylix integration
#
# Usage in home.nix:
#
#   {
#     imports = [ inputs.rofi-suite.homeManagerModules.default ];
#
#     programs.rofi-suite = {
#       enable = true;
#       themeType = "rounded";
#       useStylixColors = true;  # default
#
#       # Per-launcher theme overrides
#       desktopThemes = {
#         drun.type = "horizontal";
#         window.type = "compact";
#       };
#       appletThemes = {
#         powermenu = { type = "rounded"; color_scheme = "dracula"; };
#       };
#     };
#   }

{ config, lib, pkgs, ... }:

let
  cfg = config.programs.rofi-suite;

  # ── Color mapping: base16 → rofi ──────────────────────────────
  # Sensible defaults that work with most base16 themes.
  #
  # base00 = default background           → background
  # base01 = lighter background (status)  → background-alt
  # base05 = default foreground            → foreground
  # base0D = functions/headings (blue)     → selected
  # base0B = classes (green)               → active
  # base08 = variables/errors (red)        → urgent
  #
  # Override via `colorMapping` option if you prefer different base16 assignments.

  defaultColorMapping = {
    background     = "base00";
    background-alt = "base01";
    foreground     = "base05";
    selected       = "base0D";
    active         = "base0B";
    urgent         = "base08";
  };

  colorMapping = defaultColorMapping // cfg.colorMapping;

  resolveColor = name:
    let base16Key = colorMapping.${name};
      hex = config.lib.stylix.colors.${base16Key};
    in "#${hex}";

  stylixRasi = lib.optionalString cfg.useStylixColors ''
    /**
     * Auto-generated by rofi-suite Home Manager module.
     * Colors derived from Stylix base16 palette.
     * Do not edit manually — changes will be overwritten on rebuild.
     *
     * Base16 mapping:
     *   ${colorMapping.background}     → background
     *   ${colorMapping.background-alt} → background-alt
     *   ${colorMapping.foreground}     → foreground
     *   ${colorMapping.selected}       → selected
     *   ${colorMapping.active}         → active
     *   ${colorMapping.urgent}         → urgent
     */
    * {
        background:     ${resolveColor "background"}FF;
        background-alt: ${resolveColor "background-alt"}FF;
        foreground:     ${resolveColor "foreground"}FF;
        selected:       ${resolveColor "selected"}FF;
        active:         ${resolveColor "active"}FF;
        urgent:         ${resolveColor "urgent"}FF;
    }
  '';

  # ── Build user_config.json ────────────────────────────────────
  baseTheme = {
    type = cfg.themeType;
    color_scheme = if cfg.useStylixColors then "stylix" else cfg.colorScheme;
  } // lib.optionalAttrs (cfg.styleOverrides != {}) {
    style_overrides = cfg.styleOverrides;
  };

  # Per-desktop-mode theme overrides: { drun = { type = "horizontal"; }; }
  # Wraps each entry in { theme = { ... }; }
  desktopConfig = lib.mapAttrs (_: opts: { theme = opts; }) cfg.desktopThemes;

  # Per-applet theme overrides: { powermenu = { type = "rounded"; color_scheme = "dracula"; }; }
  # Wraps each entry in { theme = { ... }; }
  appletThemeConfig = lib.mapAttrs (_: opts: { theme = opts; }) cfg.appletThemes;

  # Merge applet themes with extraConfig (extraConfig takes precedence)
  appletOverrides = appletThemeConfig // cfg.extraConfig;

  userConfig = lib.filterAttrs (_: v: v != {}) {
    theme = baseTheme;
    desktop = desktopConfig;
    applets = appletOverrides;
  };

  userConfigJson = builtins.toJSON userConfig;

  # ── Build the theme with injected stylix colors ───────────────
  # We use overrideAttrs to inject a preBuild hook that writes
  # generated config files into the source tree before build-theme.sh runs.
  # This keeps default.nix simple — it just runs build-theme.sh on the source.
  rofiSuitePackage = cfg.package.overrideAttrs (old: {
    preBuild = ''
      # Inject generated user_config.json with the user's theme options
      cp "${pkgs.writeText "user_config.json" userConfigJson}" user_config.json
    '' + lib.optionalString cfg.useStylixColors ''
      # Inject generated stylix color scheme into the template directory
      mkdir -p templates/colors
      cp "${pkgs.writeText "stylix.rasi" stylixRasi}" templates/colors/stylix.rasi
    '';
  });

  # ── Directory structure ────────────────────────────────────────
  # Config files go in  ~/.config/rofi/suite/
  # Scripts/assets go in ~/.config/rofi/
  # Both scripts (rofi-menu, rofi-desktop) resolve from suite/
in {
  options.programs.rofi-suite = {
    enable = lib.mkEnableOption "rofi-suite modular theme suite";

    package = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = null;
      defaultText = lib.literalExpression "import ../. { pkgs = pkgs; }";
      description = ''
        Base rofi-suite package. When null (default), uses the flake's package.
        Override if you need a custom build or want to skip the build step.
      '';
    };

    themeType = lib.mkOption {
      type = lib.types.enum [ "rounded" "horizontal" "compact" "bordered" "iconic" ];
      default = "bordered";
      description = "The global default rofi theme type (layout).";
    };

    colorScheme = lib.mkOption {
      type = lib.types.str;
      default = "nord";
      description = ''
        Global default color scheme name (used when useStylixColors is false).
        Must match a file in templates/colors/<name>.rasi.
      '';
    };

    useStylixColors = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Whether to generate colors from the Stylix base16 palette.
        When true, the module reads config.lib.stylix.colors and
        generates the stylix.rasi color scheme, which is then baked
        into the assembled theme at build time.
      '';
    };

    colorMapping = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {};
      example = {
        selected = "base0E";
        urgent = "base09";
      };
      description = ''
        Override which base16 color is used for each rofi variable.
        Keys: background, background-alt, foreground, selected, active, urgent.
        Values: base16 color names (base00 through base0F).
      '';
    };

    styleOverrides = lib.mkOption {
      type = lib.types.attrs;
      default = {};
      example = {
        border-radius = "10px";
        padding = "20px";
      };
      description = "Style overrides applied on top of the global theme type.";
    };

    desktopThemes = lib.mkOption {
      type = lib.types.attrsOf lib.types.attrs;
      default = {};
      example = {
        drun.type = "horizontal";
        window.type = "compact";
      };
      description = ''
        Per-desktop-mode theme overrides. Each key is a mode name
        (drun, run, filebrowser, window) and the value is an attrset
        with optional "type" and "color_scheme" keys. When a key is
        omitted, the global default is used.
      '';
    };

    appletThemes = lib.mkOption {
      type = lib.types.attrsOf lib.types.attrs;
      default = {};
      example = {
        powermenu = { type = "rounded"; color_scheme = "dracula"; };
        volume.type = "compact";
      };
      description = ''
        Per-applet theme overrides. Each key is an applet name
        (powermenu, volume, etc.) and the value is an attrset
        with optional "type" and "color_scheme" keys. When a key is
        omitted, the global default is used.
      '';
    };

    extraConfig = lib.mkOption {
      type = lib.types.attrs;
      default = {};
      description = ''
        Additional applet configuration overrides merged into user_config.json.
        Use this to customize applets, commands, or layout overrides.
        Takes precedence over appletThemes for the same applet.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # ── Install scripts to ~/.config/rofi/ ───────────────────────
    home.packages = [ rofiSuitePackage ];

    # Symlink scripts into ~/.config/rofi/bin/
    home.file."/.config/rofi/bin".source = "${rofiSuitePackage}/share/rofi-suite/bin";
    home.file."/.config/rofi/bin".recursive = true;

    # ── Deploy theme files to ~/.config/rofi/suite/ ──────────────
    # Deploy the entire styles/ directory (all type+color combinations)
    home.file."/.config/rofi/suite/styles".source =
      "${rofiSuitePackage}/share/rofi-suite/styles";
    home.file."/.config/rofi/suite/styles".recursive = true;

    # Shipped defaults.json
    home.file."/.config/rofi/suite/defaults.json".source =
      "${rofiSuitePackage}/share/rofi-suite/defaults.json";

    # Generated user_config.json
    xdg.configFile."rofi/suite/user_config.json" = {
      text = userConfigJson;
    };
  };
}
